#!/usr/bin/perl

use warnings;
use strict;

my $SPC = q{ };
my $UND = q{_};
my $SEP = q{|};
my $END = "\n";

my @inp = <STDIN>;
my $len = $inp[0];
my $wid = $inp[1];
chomp $wid;

sub printwall {

    my($left, $middle, $l, $w) = @_;

	print $left;

    for(0..($l - 1)) {
        for(1..($w + 2)) { print $middle; }
        print $left;
    }
    print $END;
	return;
}

sub printchar {

    my($left, $middle, $l, $w) = @_;

	print $left;

    for(0..($l - 1)) {

        my @temp = split ' ', $inp[$_ + 2];

        my $star = 0;
        if (($#temp) >= 1) { $star = 1;    }

        my $mid = sprintf "%d", (($w + 2) /2);
        for(1..($w + 2)) {
            if (($_ == $mid) && ($star == 1)) { print "*"; }
            else { print $middle; }
        }
        print $left;
    }
    print $END;
}

sub printnum {

    my($left, $middle, $l, $w) = @_;

	print $left;

	my $format = join '', q{%}, $w, q{d};
    for(0..($l - 1)) {
        my @temp = split ' ', $inp[$_ + 2];

        my $num = sprintf($format, $temp[0]);

        print join '', $middle, $num, $middle, $left;
    }
    print $END;
	return;
}

printwall($SPC, $UND, $len, $wid);
printchar($SEP, $SPC, $len, $wid);
printnum ($SEP, $SPC, $len, $wid);
printwall($SEP, $UND, $len, $wid);
